//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTradingAnalysis.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTradingAnalysis.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefiniert.
        /// </summary>
        internal static string Display_SQN0 {
            get {
                return ResourceManager.GetString("Display_SQN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viele Verluste.
        /// </summary>
        internal static string Display_SQN1 {
            get {
                return ResourceManager.GetString("Display_SQN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenige Verluste.
        /// </summary>
        internal static string Display_SQN2 {
            get {
                return ResourceManager.GetString("Display_SQN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullsummenspiel.
        /// </summary>
        internal static string Display_SQN3 {
            get {
                return ResourceManager.GetString("Display_SQN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handelbar.
        /// </summary>
        internal static string Display_SQN4 {
            get {
                return ResourceManager.GetString("Display_SQN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnitt.
        /// </summary>
        internal static string Display_SQN5 {
            get {
                return ResourceManager.GetString("Display_SQN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gut.
        /// </summary>
        internal static string Display_SQN6 {
            get {
                return ResourceManager.GetString("Display_SQN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehr gut.
        /// </summary>
        internal static string Display_SQN7 {
            get {
                return ResourceManager.GetString("Display_SQN7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exzellent.
        /// </summary>
        internal static string Display_SQN8 {
            get {
                return ResourceManager.GetString("Display_SQN8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heiliger Gral.
        /// </summary>
        internal static string Display_SQN9 {
            get {
                return ResourceManager.GetString("Display_SQN9", resourceCulture);
            }
        }
    }
}
