namespace StockTradingAnalysis.Interfaces.Queries
{
    /// <summary>
    /// Defines a base interface for a dispatcher that delegates the given query to 
    /// the corresponding <see cref="IQueryHandler{TQuery,TResult}"/> implementation
    /// </summary>
    public interface IQueryDispatcher
    {
        /// <summary>
        /// Delegates the specified query to a <see cref="IQueryHandler{TQuery,TResult}" /> implementation.
        /// </summary>
        /// <typeparam name="TResult">The type of the result.</typeparam>
        /// <param name="query">The query.</param>
        /// <returns>The result generated by the <see cref="IQueryHandler{TQuery,TResult}" /></returns>
        TResult Execute<TResult>(IQuery<TResult> query);
    }
}
